/**
 * Article Actions
 * @type {string}
 */
export const GET_ARTICLES = 'GET_ARTICLES';


/**
 * Candidate Actions
 * @type {string}
 */
export const BEGIN_GET_CANDIDATE = 'BEGIN_GET_CANDIDATE';
export const GET_CANDIDATE_SUCCESS = ' GET_CANDIDATE_SUCCESS';
export const GET_CANDIDATE_FAILURE = ' GET_CANDIDATE_FAILURE';

/**
 * Vacancy Actions
 * @type {string}
 */
export const BEGIN_GET_POSITION = 'BEGIN_GET_POSITION';
export const GET_POSITION_SUCCESS = 'GET_POSITION_SUCCESS';
export const GET_POSITION_FAILURE = 'GET_POSITION_FAILURE';


export const BEGIN_GET_ACTIVE_POSITION = 'BEGIN_GET_ACTIVE_POSITION';
export const GET_ACTIVE__POSITION_SUCCESS = 'GET_ACTIVE__POSITION_SUCCESS';
export const GET_ACTIVE_POSITION_FAILURE = 'GET_ACTIVE_POSITION_FAILURE';

export const BEGIN_POST_POSITION = 'BEGIN_POST_POSITION';
export const POST_POSITION_SUCCESS = 'POST_POSITION_SUCCESS';
export const POST_POSITION_FAILURE = 'POST_POSITION_FAILURE';


/**
 * QUALIFICATION Actions
 * @type {string}
 */
export const BEGIN_GET_QUALIFICATION = 'BEGIN_GET_QUALIFICATION';
export const GET_QUALIFICATION_SUCCESS = 'GET_QUALIFICATION_SUCCESS';
export const GET_QUALIFICATION_FAILURE = 'GET_QUALIFICATION_FAILURE';
